apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: service-b-v1-gateway
  namespace: istio-meshlab
  labels:
    app: service-b-v1
spec:
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "service-b-v1.local"
