apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: service-a-gateway
  namespace: istio-meshlab
  labels:
    app: service-a
spec:
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: service-a-tls
      hosts:
        - "service-a.local"
