apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-v2
  namespace: istio-meshlab
  labels:
    app: service-b
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
      version: v2
  template:
    metadata:
      labels:
        app: service-b
        version: v2
    spec:
      containers:
        - name: service-b-v2
          image: quarkus-istio-service:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_REST_CLIENT_EXTERNAL_API_URL
              value: "http://service-b"
            - name: MESHLAB_SERVICE_NAME
              value: "service-b-v2"